name: food_card
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  qr_code_scanner: ^1.0.1
  dartz: ^0.10.0-nullsafety.2
  get: 4.6.5
  internet_connection_checker: ^1.0.0+1
  modal_bottom_sheet: ^2.1.2
#  shared_preferences: ^2.0.17
  dio: ^5.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts: 
    - family: Questrial
      fonts: 
        - asset: fonts/Questrial-Regular.ttf
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
    - family: Quantico
      fonts: 
        - asset: fonts/Quantico-Regular.otf
  uses-material-design: true

